spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      properties:
        spring.json.add.type.headers: false
        max.request.size: ${KAFKA_MAX_MESSAGE_SIZE}
        buffer.memory: ${KAFKA_BUFFER_MEMORY}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

configs:
  input-directory: /input
  chunk-size: ${CHUNK_SIZE}
  temp-directory: /tmp/chunks

kafka:
  topic:
    device-config: device-config-topic